[package]
name = "bwk-hwi-cli"
readme = "README.md"
description = "HWI CLI"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license = "MIT AND BSD-3-Clause"
repository.workspace = true
keywords.workspace = true

[[bin]]
name = "hwi"
path = "src/bin/hwi.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
bitcoin = "0.32"
hex = "0.4"
bwk-hwi = { version = "0.1.0", path = "../" }
